import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const allowOrigin = (request: Request) => request.headers.get('Origin') || 'http://localhost:8000';
const headers = (request: Request) => ({ 'Access-Control-Allow-Origin': allowOrigin(request), 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods': 'POST, OPTIONS', Vary: 'Origin' });
const response = (request: Request, body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...headers(request), 'Content-Type': 'application/json' } });
const ok = (request: Request, data: unknown = {}) => response(request, { success: true, ...data });
const fail = (request: Request, code: string, message: string, status = 400) => response(request, { success: false, error: { code, message } }, status);
const clean = (value: unknown, max = 300) => String(value || '').trim().slice(0, max);
const toolRegistry = ['get_business_profile', 'get_products', 'get_customers', 'get_business_metrics', 'get_sales_summary', 'get_inventory_summary', 'get_recent_activity', 'get_tasks', 'generate_business_report', 'create_task'].map(name => ({ name, description: name.replaceAll('_', ' '), access_level: name === 'create_task' ? 'WRITE' : 'READ' }));
const resourceRegistry = ['profile', 'products', 'customers', 'metrics', 'reports', 'tasks'].map(name => ({ uri: `business://${name}`, name, description: `Business-scoped ${name} data.` }));
const promptRegistry = ['business_health_report', 'sales_analysis', 'marketing_analysis', 'inventory_analysis', 'monthly_business_summary'].map(name => ({ name, description: name.replaceAll('_', ' ') }));

async function userContext(request: Request) { const authorization = request.headers.get('Authorization'); if (!authorization) throw new Error('AUTHENTICATION_REQUIRED'); const client = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_ANON_KEY')!, { global: { headers: { Authorization: authorization } }, auth: { persistSession: false, autoRefreshToken: false } }); const { data: { user }, error } = await client.auth.getUser(); if (error || !user) throw new Error('AUTHENTICATION_REQUIRED'); const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth: { persistSession: false } }); const { data: business } = await admin.from('businesses').select('id').eq('owner_id', user.id).maybeSingle(); if (!business) throw new Error('BUSINESS_NOT_FOUND'); return { admin, user, business }; }
function bytes(value: string) { return Uint8Array.from(atob(value), char => char.charCodeAt(0)); }
function base64(value: Uint8Array) { return btoa(String.fromCharCode(...value)); }
async function keyMaterial() { const secret = Deno.env.get('MCP_ENCRYPTION_KEY'); if (!secret || secret.length < 32) throw new Error('MCP_ENCRYPTION_KEY is not configured.'); const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(secret)); return crypto.subtle.importKey('raw', digest, 'AES-GCM', false, ['encrypt', 'decrypt']); }
async function encryptSecret(value: string) { if (!value) return { ciphertext: null, iv: null }; const iv = crypto.getRandomValues(new Uint8Array(12)); const cipher = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await keyMaterial(), new TextEncoder().encode(value)); return { ciphertext: base64(new Uint8Array(cipher)), iv: base64(iv) }; }
async function decryptSecret(ciphertext: string | null, iv: string | null) { if (!ciphertext || !iv) return ''; const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: bytes(iv) }, await keyMaterial(), bytes(ciphertext)); return new TextDecoder().decode(plain); }
function safeEndpoint(value: string) { try { const url = new URL(value); const host = url.hostname.toLowerCase(); return url.protocol === 'https:' && !['localhost', '127.0.0.1', '::1'].includes(host) && !host.endsWith('.internal') && !/^10\.|^192\.168\.|^169\.254\.|^172\.(1[6-9]|2\d|3[0-1])\./.test(host); } catch { return false; } }
async function externalRequest(connection: any, method: string, params: unknown, secret: string) { const auth = connection.auth_type === 'bearer' || connection.auth_type === 'oauth2' ? { Authorization: `Bearer ${secret}` } : {}; const result = await fetch(connection.endpoint_url, { method: 'POST', headers: { Accept: 'application/json, text/event-stream', 'Content-Type': 'application/json', ...auth }, body: JSON.stringify({ jsonrpc: '2.0', id: crypto.randomUUID(), method, params }) }); const text = await result.text(); let data: any; try { data = JSON.parse(text); } catch { const match = [...text.matchAll(/data:\s*(\{.*\})/g)].pop(); data = match ? JSON.parse(match[1]) : null; } if (result.status === 401 || result.status === 403) throw new Error('AUTHENTICATION_REQUIRED'); if (!result.ok || !data) throw new Error('EXTERNAL_MCP_ERROR'); if (data.error) throw new Error(clean(data.error.message, 300) || 'EXTERNAL_MCP_ERROR'); return data.result || {}; }

Deno.serve(async request => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: headers(request) });
  if (request.method !== 'POST') return fail(request, 'METHOD_NOT_ALLOWED', 'Use POST.', 405);
  try { const { admin, user, business } = await userContext(request); const input = await request.json(); const action = clean(input.action, 50);
    if (action === 'overview') { const [connections, clients, logs, external, oauthGrants] = await Promise.all([admin.from('mcp_connections').select('id,app_name,created_at,last_used_at,revoked_at,expires_at,request_count').eq('user_id', user.id).order('created_at', { ascending: false }), admin.from('mcp_clients').select('id,connection_id,client_name,client_version,status,connected_at,last_activity_at,request_count').eq('user_id', user.id).order('last_activity_at', { ascending: false }), admin.from('mcp_access_log').select('id,operation,client_name,tool_name,resource_uri,prompt_name,requested_at,success,error_code,error_message').eq('user_id', user.id).order('requested_at', { ascending: false }).limit(50), admin.from('mcp_external_connections').select('id,name,endpoint_url,auth_type,enabled,status,last_checked_at,last_error,discovered_tools,discovered_resources,discovered_prompts,created_at,updated_at').eq('user_id', user.id).order('updated_at', { ascending: false }), admin.from('mcp_oauth_grants').select('id,client_id,scopes,approved_at,revoked_at').eq('user_id', user.id).order('approved_at', { ascending: false })]); if (connections.error || clients.error || logs.error || external.error || oauthGrants.error) throw new Error('MCP data could not be loaded.'); return ok(request, { server: { name: 'Elio MCP Server', version: '1.1.0', status: 'active', endpoint: 'Public Vercel /mcp endpoint', last_activity_at: logs.data?.[0]?.requested_at || null }, capabilities: { tools: toolRegistry, resources: resourceRegistry, prompts: promptRegistry }, connections: connections.data || [], oauth_grants: oauthGrants.data || [], clients: clients.data || [], activity: logs.data || [], external_connections: (external.data || []).map(item => ({ ...item, tools: item.discovered_tools || [], resources: item.discovered_resources || [], prompts: item.discovered_prompts || [] })) }); }
    if (action === 'revoke_oauth_grant') { const grantId = clean(input.grant_id, 80), revokedAt = new Date().toISOString(); const { data: grant, error } = await admin.from('mcp_oauth_grants').update({ revoked_at: revokedAt }).eq('id', grantId).eq('user_id', user.id).select('id').maybeSingle(); if (error || !grant) throw new Error('OAuth authorization could not be revoked.'); await Promise.all([admin.from('mcp_oauth_access_tokens').update({ revoked_at: revokedAt }).eq('grant_id', grant.id).is('revoked_at', null), admin.from('mcp_oauth_refresh_tokens').update({ revoked_at: revokedAt }).eq('grant_id', grant.id).is('revoked_at', null)]); return ok(request); }
    if (action === 'set_permission') { const access = clean(input.access_level, 20); if (!['READ', 'WRITE', 'SENSITIVE'].includes(access)) return fail(request, 'INVALID_ACCESS_LEVEL', 'Unsupported access level.'); const { data: connection } = await admin.from('mcp_connections').select('id').eq('id', clean(input.connection_id, 80)).eq('user_id', user.id).maybeSingle(); if (!connection) return fail(request, 'NOT_FOUND', 'MCP client not found.', 404); const { error } = await admin.from('mcp_permissions').upsert({ connection_id: connection.id, user_id: user.id, capability_name: clean(input.capability_name, 120), access_level: access, enabled: Boolean(input.enabled), updated_at: new Date().toISOString() }, { onConflict: 'connection_id,capability_name' }); if (error) throw new Error('Permission could not be saved.'); return ok(request); }
    if (action === 'create_external') { const name = clean(input.name, 120), endpoint = clean(input.endpoint_url, 500), authType = clean(input.auth_type, 20) || 'none'; if (!name || !safeEndpoint(endpoint)) return fail(request, 'INVALID_ENDPOINT', 'Use a valid HTTPS MCP endpoint.'); if (!['none', 'bearer', 'oauth2'].includes(authType)) return fail(request, 'INVALID_AUTH_TYPE', 'Unsupported authentication method.'); if (authType !== 'none' && !clean(input.secret, 4000)) return fail(request, 'CREDENTIAL_REQUIRED', 'A credential is required for this authentication method.'); const encrypted = await encryptSecret(clean(input.secret, 4000)); const { data, error } = await admin.from('mcp_external_connections').insert({ user_id: user.id, name, endpoint_url: endpoint, auth_type: authType, auth_secret_ciphertext: encrypted.ciphertext, auth_secret_iv: encrypted.iv, enabled: true, status: 'disconnected' }).select('id').single(); if (error) throw new Error('External MCP service could not be saved.'); return ok(request, { id: data.id }); }
    if (action === 'test_external') { const { data: connection } = await admin.from('mcp_external_connections').select('*').eq('id', clean(input.id, 80)).eq('user_id', user.id).maybeSingle(); if (!connection) return fail(request, 'NOT_FOUND', 'External MCP service not found.', 404); if (!connection.enabled) return fail(request, 'DISABLED', 'This external MCP service is disabled.'); let discovered; try { const secret = await decryptSecret(connection.auth_secret_ciphertext, connection.auth_secret_iv); const initialize = await externalRequest(connection, 'initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'Elio', version: '1.0.0' } }, secret); const [toolResult, resourceResult, promptResult] = await Promise.all([externalRequest(connection, 'tools/list', {}, secret), externalRequest(connection, 'resources/list', {}, secret), externalRequest(connection, 'prompts/list', {}, secret)]); discovered = { discovered_tools: toolResult.tools || [], discovered_resources: resourceResult.resources || [], discovered_prompts: promptResult.prompts || [] }; const { error } = await admin.from('mcp_external_connections').update({ ...discovered, status: 'connected', last_checked_at: new Date().toISOString(), last_error: null, updated_at: new Date().toISOString() }).eq('id', connection.id).eq('user_id', user.id); if (error) throw new Error('Connection state could not be saved.'); return ok(request, { server_info: initialize.serverInfo || null, capabilities: discovered }); } catch (error) { const code = error instanceof Error && error.message === 'AUTHENTICATION_REQUIRED' ? 'authentication_required' : 'error'; await admin.from('mcp_external_connections').update({ status: code, last_checked_at: new Date().toISOString(), last_error: code === 'authentication_required' ? 'The external service requires valid credentials.' : 'The external MCP endpoint could not be reached or did not respond correctly.', updated_at: new Date().toISOString() }).eq('id', connection.id).eq('user_id', user.id); return fail(request, code.toUpperCase(), code === 'authentication_required' ? 'The external service requires valid credentials.' : 'The external MCP endpoint could not be reached or did not respond correctly.', 502); } }
    if (action === 'set_external_enabled') { const id = clean(input.id, 80), enabled = Boolean(input.enabled); const { error } = await admin.from('mcp_external_connections').update({ enabled, status: enabled ? 'disconnected' : 'disabled', updated_at: new Date().toISOString() }).eq('id', id).eq('user_id', user.id); if (error) throw new Error('External MCP state could not be updated.'); return ok(request); }
    if (action === 'disconnect_external') { const { error } = await admin.from('mcp_external_connections').update({ enabled: false, status: 'disabled', auth_secret_ciphertext: null, auth_secret_iv: null, updated_at: new Date().toISOString() }).eq('id', clean(input.id, 80)).eq('user_id', user.id); if (error) throw new Error('External MCP service could not be disconnected.'); return ok(request); }
    return fail(request, 'UNKNOWN_ACTION', 'Unsupported MCP administration action.');
  } catch (error) { const code = error instanceof Error ? error.message : 'MCP_ADMIN_ERROR'; if (code === 'AUTHENTICATION_REQUIRED') return fail(request, code, 'Authentication required.', 401); if (code === 'BUSINESS_NOT_FOUND') return fail(request, code, 'Complete Elio onboarding first.', 403); return fail(request, 'MCP_ADMIN_ERROR', 'The MCP administration service could not complete that request.', 500); }
});
